// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUHe_mjjkXw5l3K2KeFgvEhXRoYy6A8o8',
    appId: '1:631146591376:web:99c4df4870b9f7b36c5415',
    messagingSenderId: '631146591376',
    projectId: 'furia-talk',
    authDomain: 'furia-talk.firebaseapp.com',
    storageBucket: 'furia-talk.firebasestorage.app',
    measurementId: 'G-JDVN49FBTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGWDpMeTtZUnZNSoS2CN7L9BpgnzylHts',
    appId: '1:631146591376:android:de3be3e68c775e786c5415',
    messagingSenderId: '631146591376',
    projectId: 'furia-talk',
    storageBucket: 'furia-talk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaepcSfcR2DnEcIuX9X_CNdrVM1Dzlwrk',
    appId: '1:631146591376:ios:b387a701836d5c8b6c5415',
    messagingSenderId: '631146591376',
    projectId: 'furia-talk',
    storageBucket: 'furia-talk.firebasestorage.app',
    iosBundleId: 'com.example.furiaTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaepcSfcR2DnEcIuX9X_CNdrVM1Dzlwrk',
    appId: '1:631146591376:ios:b387a701836d5c8b6c5415',
    messagingSenderId: '631146591376',
    projectId: 'furia-talk',
    storageBucket: 'furia-talk.firebasestorage.app',
    iosBundleId: 'com.example.furiaTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUHe_mjjkXw5l3K2KeFgvEhXRoYy6A8o8',
    appId: '1:631146591376:web:3960d45bf44caffd6c5415',
    messagingSenderId: '631146591376',
    projectId: 'furia-talk',
    authDomain: 'furia-talk.firebaseapp.com',
    storageBucket: 'furia-talk.firebasestorage.app',
    measurementId: 'G-P48F5EKS4X',
  );
}
